### PR TITLE
Feature/158/use deploy key with travis

### PR DESCRIPTION
**Pull request by garyluu**
So after Travis generates the docs and stuff on the VM, what Travis offers is:
1. Copy everything in the current working branch (feature/158/useDeployKeyWithTravis for example) to replace what's on gh-pages branch
2. Copy a specific directory in the current working branch to replace what's on gh-pages

Number 1 has too much junk that should not be on gh-pages so that's bad
Number 2 is troublesome because there's a lot of files that the current branch doesn't know about.

In either case, it appears a checkout of the existing gh-pages branch is unavoidable which means the benefit of using the Travis deploy mechanism is severely diminished.

Anyways, here's a draft PR where the Travis deploy mechanism is used. The downside is that any additional artifacts that result from the build (like node_modules), may end up in gh-pages by accident unless intentionally removed. The upside is...it looks prettier?

The two scripts added to this branch isn't actually needed right now (since we're checking out the gh-pages branch still). If approved, those scripts will be removed before making a real PR to GA4GH.

So the question is...is this PR worth merging to GA4GH?

### CODE REVIEW

**Comment by denis-yuen** [comment]
(for @coverbeck ticket is https://github.com/ga4gh/tool-registry-service-schemas/issues/158 )

For additional background:
1) would this approach be more secure than the current approach?
2) what kind of plan is ga4gh on actually? Should we be moving off of travis actually and would that help?

**Comment by garyluu** [comment]
> (for @coverbeck ticket is [ga4gh#158](https://github.com/ga4gh/tool-registry-service-schemas/issues/158) )
> 
> For additional background:
> 
> 1. would this approach be more secure than the current approach?
> 2. what kind of plan is ga4gh on actually? Should we be moving off of travis actually and would that help?

1. Security-wise, no.  It should not be any more secure. It's still using a deploy key. Less prone to error? Unclear
2. GA4GH WES is using Travis with personal access token. Their gh-pages has a bunch of junk and only the preview directory is related.  Moving off Travis likely wouldn't help, would still end up using the current workaround.

**Comment by garyluu** [comment]
Another option is I keep a copy of the gh-pages in all branches to circumvent checking out the gh-pages branch during CI

**Comment by denis-yuen** [comment]
Thanks, I don't have a strong opinion on the PR specifically, I think I'm ok with your recommendation. 

That said, it looks like GA4GH they're still on travis-ci.org which IIRC dies at the end of the year. 
Can be new ticket, but might have to be done sooner rather than later.

**Comment by garyluu** [comment]
My recommendation? Hmm...I think I recommend closing the issue and linking to this PR.  Not enough benefits to warrant the change. If we do plan to move away from Travis for any reason, it makes it harder.

**Comment by denis-yuen** [comment]
Sounds good.

**Pull request closed without merging**
